export default {
  en: { manage_a11y: "iYiYi Pro: manage", pro_title: "You're on iYiYi Pro", pro_text: "Your profile is shown first.", manage: "Manage", pill_a11y: "Go Pro", pill: "Go Pro · get seen first", card_a11y: "Go Pro: get seen first", card_title: "Get seen first with iYiYi Pro", card_text: "Show up ahead of free profiles nearby.", go_pro: "Go Pro" },
  es: { manage_a11y: "iYiYi Pro: gestionar", pro_title: "Ya tienes iYiYi Pro", pro_text: "Tu perfil se muestra primero.", manage: "Gestionar", pill_a11y: "Hazte Pro", pill: "Hazte Pro · aparece primero", card_a11y: "Hazte Pro: aparece primero", card_title: "Aparece primero con iYiYi Pro", card_text: "Sal antes que los perfiles gratuitos cerca de ti.", go_pro: "Hazte Pro" },
  zh: { manage_a11y: "iYiYi Pro：管理", pro_title: "你已是 iYiYi Pro 会员", pro_text: "你的个人资料会优先展示。", manage: "管理", pill_a11y: "升级 Pro", pill: "升级 Pro · 优先展示", card_a11y: "升级 Pro：优先展示", card_title: "用 iYiYi Pro 优先展示", card_text: "在附近排在免费用户之前。", go_pro: "升级 Pro" },
  ja: { manage_a11y: "iYiYi Pro：管理", pro_title: "iYiYi Pro に登録中です", pro_text: "あなたのプロフィールが優先表示されます。", manage: "管理", pill_a11y: "Pro にする", pill: "Pro にする · 優先表示", card_a11y: "Pro にする：優先表示", card_title: "iYiYi Pro で優先的に表示", card_text: "近くの無料プロフィールより先に表示されます。", go_pro: "Pro にする" },
  ko: { manage_a11y: "iYiYi Pro: 관리", pro_title: "iYiYi Pro 이용 중", pro_text: "내 프로필이 먼저 표시돼요.", manage: "관리", pill_a11y: "Pro 시작하기", pill: "Pro 시작하기 · 먼저 보여지기", card_a11y: "Pro 시작하기: 먼저 보여지기", card_title: "iYiYi Pro로 먼저 보여지세요", card_text: "주변의 무료 프로필보다 먼저 표시돼요.", go_pro: "Pro 시작" },
  fr: { manage_a11y: "iYiYi Pro : gérer", pro_title: "Vous avez iYiYi Pro", pro_text: "Votre profil s'affiche en premier.", manage: "Gérer", pill_a11y: "Passer à Pro", pill: "Passer à Pro · soyez vu en premier", card_a11y: "Passer à Pro : apparaissez en premier", card_title: "Apparaissez en premier avec iYiYi Pro", card_text: "Passez devant les profils gratuits à proximité.", go_pro: "Passer à Pro" },
  de: { manage_a11y: "iYiYi Pro: verwalten", pro_title: "Du hast iYiYi Pro", pro_text: "Dein Profil wird zuerst angezeigt.", manage: "Verwalten", pill_a11y: "Pro holen", pill: "Pro holen · zuerst gesehen werden", card_a11y: "Pro holen: zuerst gesehen werden", card_title: "Mit iYiYi Pro zuerst gesehen werden", card_text: "Erscheine in der Nähe vor kostenlosen Profilen.", go_pro: "Pro holen" },
  pt: { manage_a11y: "iYiYi Pro: gerenciar", pro_title: "Você tem o iYiYi Pro", pro_text: "Seu perfil aparece primeiro.", manage: "Gerenciar", pill_a11y: "Seja Pro", pill: "Seja Pro · apareça primeiro", card_a11y: "Seja Pro: apareça primeiro", card_title: "Apareça primeiro com o iYiYi Pro", card_text: "Fique à frente dos perfis gratuitos por perto.", go_pro: "Seja Pro" },
  ar: { manage_a11y: "iYiYi Pro: إدارة", pro_title: "أنت مشترك في iYiYi Pro", pro_text: "يظهر ملفك الشخصي أولاً.", manage: "إدارة", pill_a11y: "اشترك في Pro", pill: "اشترك في Pro · اظهر أولاً", card_a11y: "اشترك في Pro: اظهر أولاً", card_title: "اظهر أولاً مع iYiYi Pro", card_text: "اظهر قبل الملفات المجانية القريبة منك.", go_pro: "اشترك في Pro" },
  hi: { manage_a11y: "iYiYi Pro: मैनेज करें", pro_title: "आप iYiYi Pro पर हैं", pro_text: "आपकी प्रोफ़ाइल सबसे पहले दिखती है।", manage: "मैनेज करें", pill_a11y: "Pro लें", pill: "Pro लें · सबसे पहले दिखें", card_a11y: "Pro लें: सबसे पहले दिखें", card_title: "iYiYi Pro के साथ सबसे पहले दिखें", card_text: "आस-पास की फ़्री प्रोफ़ाइल से पहले दिखें।", go_pro: "Pro लें" },
  tl: { manage_a11y: "iYiYi Pro: pamahalaan", pro_title: "Naka-iYiYi Pro ka na", pro_text: "Nauunang ipinapakita ang profile mo.", manage: "Pamahalaan", pill_a11y: "Mag-Pro", pill: "Mag-Pro · mauna kang makita", card_a11y: "Mag-Pro: mauna kang makita", card_title: "Mauna kang makita gamit ang iYiYi Pro", card_text: "Mauna sa mga libreng profile sa malapit.", go_pro: "Mag-Pro" },
}
