// Shared by TabBar (members) and GuestTabBar (logged out).
export default {
  en: { explore: 'Explore', discover: 'Discover', feed: 'Feed', arcade: 'Arcade', home: 'Home', map: 'Map', profile: 'Profile', lockedTab: '{label} (sign up to use)', cameraLocked: 'Camera (sign up to use)', openCamera: 'Open camera', signUp: 'Sign up', signUpFree: 'Sign up free' },
  es: { explore: 'Explorar', discover: 'Descubrir', feed: 'Feed', arcade: 'Arcade', home: 'Inicio', map: 'Mapa', profile: 'Perfil', lockedTab: '{label} (regístrate para usarlo)', cameraLocked: 'Cámara (regístrate para usarla)', openCamera: 'Abrir cámara', signUp: 'Registrarse', signUpFree: 'Regístrate gratis' },
  zh: { explore: '探索', discover: '发现', feed: '动态', arcade: '游戏厅', home: '首页', map: '地图', profile: '个人资料', lockedTab: '{label}（注册后可用）', cameraLocked: '相机（注册后可用）', openCamera: '打开相机', signUp: '注册', signUpFree: '免费注册' },
  ja: { explore: '探索', discover: '発見', feed: 'フィード', arcade: 'アーケード', home: 'ホーム', map: 'マップ', profile: 'プロフィール', lockedTab: '{label}（登録すると利用できます）', cameraLocked: 'カメラ（登録すると利用できます）', openCamera: 'カメラを開く', signUp: '登録', signUpFree: '無料で登録' },
  ko: { explore: '탐색', discover: '발견', feed: '피드', arcade: '아케이드', home: '홈', map: '지도', profile: '프로필', lockedTab: '{label} (가입 후 이용 가능)', cameraLocked: '카메라 (가입 후 이용 가능)', openCamera: '카메라 열기', signUp: '가입하기', signUpFree: '무료로 가입하기' },
  fr: { explore: 'Explorer', discover: 'Découvrir', feed: 'Fil', arcade: 'Arcade', home: 'Accueil', map: 'Carte', profile: 'Profil', lockedTab: "{label} (inscrivez-vous pour l'utiliser)", cameraLocked: "Caméra (inscrivez-vous pour l'utiliser)", openCamera: "Ouvrir l'appareil photo", signUp: "S'inscrire", signUpFree: 'Inscription gratuite' },
  de: { explore: 'Erkunden', discover: 'Entdecken', feed: 'Feed', arcade: 'Arcade', home: 'Start', map: 'Karte', profile: 'Profil', lockedTab: '{label} (Registrierung nötig)', cameraLocked: 'Kamera (Registrierung nötig)', openCamera: 'Kamera öffnen', signUp: 'Registrieren', signUpFree: 'Kostenlos registrieren' },
  pt: { explore: 'Explorar', discover: 'Descobrir', feed: 'Feed', arcade: 'Arcade', home: 'Início', map: 'Mapa', profile: 'Perfil', lockedTab: '{label} (cadastre-se para usar)', cameraLocked: 'Câmera (cadastre-se para usar)', openCamera: 'Abrir câmera', signUp: 'Cadastrar', signUpFree: 'Cadastre-se grátis' },
  ar: { explore: 'استكشاف', discover: 'اكتشف', feed: 'الموجز', arcade: 'الألعاب', home: 'الرئيسية', map: 'الخريطة', profile: 'حسابي', lockedTab: '{label} (سجّل لاستخدامه)', cameraLocked: 'الكاميرا (سجّل لاستخدامها)', openCamera: 'فتح الكاميرا', signUp: 'إنشاء حساب', signUpFree: 'سجّل مجانًا' },
  hi: { explore: 'एक्सप्लोर', discover: 'खोजें', feed: 'फ़ीड', arcade: 'आर्केड', home: 'होम', map: 'मैप', profile: 'प्रोफ़ाइल', lockedTab: '{label} (इस्तेमाल के लिए साइन अप करें)', cameraLocked: 'कैमरा (इस्तेमाल के लिए साइन अप करें)', openCamera: 'कैमरा खोलें', signUp: 'साइन अप', signUpFree: 'मुफ़्त में साइन अप करें' },
  tl: { explore: 'Galugarin', discover: 'Tuklasin', feed: 'Feed', arcade: 'Arcade', home: 'Home', map: 'Mapa', profile: 'Profile', lockedTab: '{label} (mag-sign up para magamit)', cameraLocked: 'Camera (mag-sign up para magamit)', openCamera: 'Buksan ang camera', signUp: 'Mag-sign up', signUpFree: 'Mag-sign up nang libre' },
}
